### ISSUE TITLE
Hiding comments / adding ability to hide comments

### ISSUE THREAD

**Issue by ulyngs** [ulyngs/open-source-no-distractions-for-youtube#1]
A few people have sent email suggestions with this - the problem is that Safari App Extensions doesn't make it nearly as easy as it should be to add user options to an extension; Apple's documentation for building extensions is *really* bad.

In the short-term, I may just update the app to hide comments, assuming that this will be in line with most users' needs; in the longer term I will look into ways to give users the ability to toggle different sections on or off.

**Comment by Teufelchen1** [comment]
Hi! Just wanted to push your motivation a bit :) I would like to not see the comments!

**Comment by ulyngs** [comment]
@Teufelchen1  does the current functionality with a button which hides comments when click, and also hides them by default if that was the latest state, not meet what you need? :)

**Comment by Teufelchen1** [comment]
I never noticed that button until now 🙈🙈😅. I'm sorry then 🙋‍♀️It does meet what I need. Thanks!

**Comment by ulyngs** [comment]
LOL, I'll try to make it explicit in the app description that this button exists... 😃
