### ISSUE TITLE
Comments under community posts

### ISSUE THREAD

**Issue by cabe9** [ulyngs/open-source-no-distractions-for-youtube#12]
When I open a community post, it is impossible to see the comments on that post, even with the comments turned on.

**Comment by ulyngs** [comment]
Thanks for flagging this: someone else mentioned this issue in a review but I never understood exactly what it referred to.

Can you send me a link / screenshots of what this means, so I can understand and fix the issue? :)

**Comment by ulyngs** [comment]
Ah I understand the issue now and can reproduce it on my computer -- thanks for clarifying!!

I will try to fix this next week or the week after and submit an updated version to the App store!

**Comment by ulyngs** [comment]
Fixed w 1b026389778c8997cc5325fa734c3bcfd4564bbf, will be included in next update

**Comment by ulyngs** [comment]
@cabe9 can you confirm that this is fixed in the update?

**Comment by cabe9** [comment]
It works now!  thank you for fixing it!
