### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by lowiebbb** [ulyngs/open-source-no-distractions-for-youtube#15]
I think this feature would be very nice to have:

- no thumbnails (just text like google search)

there are also some cosmetic requests i have:
- removing empty home tab when recommended feed is turned off (and redirecting the yt logo on the top left to the subsription tab)
- removing the empty space below a video when up next is turned off

thx for the nice extension!
-

**Comment by lowiebbb** [comment]
Yes exactly! I appreciate the effort you put in this app man!On 7 Oct 2022, at 10:17, Ulrik Lyngs ***@***.***> wrote:﻿
Ah great suggestions!
By 'no thumbnails', do you mean that the preview photos of a video should be replaced with just a text description, or something like that?

**Comment by ulyngs** [comment]
In order to include this, I'll first need to find a solution to #7 -- obviously, we can't have this happen by default, the user would need to opt in to it

**Comment by ulyngs** [comment]
Added ability to hide thumbnails w/ 2332ed8cb0b9bb1f109dd000f524e3f88e1876b7

**Comment by ulyngs** [comment]
What did you mean by "removing empty home tab when recommended feed is turned off (and redirecting the yt logo on the top left to the subsription tab)"? That you'd like the subscriptions to be the landing page? I prefer that the home page is empty when the recommended feed is turned off, to avoid distraction?
