### ISSUE TITLE
Comments do not load when turned ON while watching video

### ISSUE THREAD

**Issue by ghurao** [ulyngs/open-source-no-distractions-for-youtube#16]
I've noticed that if the comments are OFF before you begin watching the video (opening video link in new tab; comments just not ON before clicking on video link), then even when comments are toggled ON, they do not load.
Even when scrolling down after toggling ON, the space for the comments is there but it is blank.

I've tried reloading the page after the comments don't load when I toggle the comments from OFF to ON for the video. But, when page is reloaded, the comments go back to the default setting, which is OFF.

**Comment by ulyngs** [comment]
Thanks a lot for flagging this!

I can't reproduce this on my computer -- can you let me know whether this is happening for you on iPhone, iPad, or Mac, and on what version of Safari?
