### ISSUE TITLE
doesn't update

### ISSUE THREAD

**Issue by YoskioMorticia** [ulyngs/open-source-no-distractions-for-youtube#17]
every time I open YouTube everything is disable and I have so select my choices again of what I want to see every time I open YouTube

**Comment by ulyngs** [comment]
Thanks for flagging this!

At the moment this is deliberate, to add a bit of friction for you to see potentially distracting content. However, I would like to add a way to opt-in to saving the status; I'm tracking this in issue #7

**Comment by ulyngs** [comment]
@YoskioMorticia I've added the ability to save settings in the latest version -- can you update the app and let me know if it fits what you had in mind?

**Comment by YoskioMorticia** [comment]
Thanks for e-mail me about the update, i was expecting that it saved by itself but you put a button to save the settings and that’s even better than saving by itself 😃 i love it, thank you so much you really don’t know how much i live the app, it helps a lot to people with OCD and that app is something i was looking for since long time ago, thank you really ❤️ A LotОтправлено с iPhoneOn Nov 22, 2022, at 02:39, Ulrik Lyngs ***@***.***> wrote:﻿
@YoskioMorticia I've added the ability to save settings in the latest version -- can you update the app and let me know if it fits what you had in mind?
