### ISSUE TITLE
Bug:  Shorts checkbox incorrectly toggling Subscriptions

### ISSUE THREAD

**Issue by donanroherty** [ulyngs/open-source-no-distractions-for-youtube#21]
The control for toggle shorts is incorrectly targeting the Subscriptions page link.  Presumably caused by a recent update to YouTube.
Issue occurring on MacOS Safari.

![shorts-toggle-bug](https://user-images.githubusercontent.com/5565439/197154999-2bf79cd8-7a5e-4f3d-920d-d113e5681737.jpg)

**Comment by ulyngs** [comment]
Thanks for flagging this! I will try to fix and submit an update asap

**Comment by ulyngs** [comment]
Fixed w/ 2c6088a8fb8cae37d839bd22bb1a361372be698a   ---  will submit an update to the app store shortly
