### ISSUE TITLE
Subscriptions button is hidden instead of Shorts.

### ISSUE THREAD

**Issue by flashyhuckle** [ulyngs/open-source-no-distractions-for-youtube#22]
On the homepage the website shows "Home" and "Shorts". When you toggle "Shorts" to be visible, "Subscriptions" appears.

**Comment by ulyngs** [comment]
Repeat of #21 

I fixed this problem this morning and have submitted an update to the app store -- it should be out in a couple of days!

**Comment by ulyngs** [comment]
Update should be out now -- can you confirm that it solves the problem?

**Comment by flashyhuckle** [comment]
Confirmed - problem is solved, thank you!
