### ISSUE TITLE
Shorts toggle hides abo section not shorts section

### ISSUE THREAD

**Issue by mueller-kai** [ulyngs/open-source-no-distractions-for-youtube#24]
<img width="499" alt="Bildschirmfoto 2022-11-20 um 18 17 14" src="https://user-images.githubusercontent.com/72653744/202916154-ebaa8783-e5cf-4bbf-b641-bf82e9f153cd.png">
<img width="499" alt="Bildschirmfoto 2022-11-20 um 18 17 22" src="https://user-images.githubusercontent.com/72653744/202916157-7fbf7d45-c33f-41f4-860d-965686340b47.png">

**Comment by mueller-kai** [comment]
Im Using safari on an M1 Mac

**Comment by ulyngs** [comment]
Can you let me know which version of the extension you are using? I thought I fixed this bug previously -- can you check that you don't have an update available on the app store?

**Comment by mueller-kai** [comment]
Update fixed it... Sorry though apple would update this automatically ...
