### ISSUE TITLE
Shorts and Subscriptions mixup for Safari on MacOS

### ISSUE THREAD

**Issue by happy-nacho** [ulyngs/open-source-no-distractions-for-youtube#25]
<img width="495" alt="Screenshot 2022-11-28 at 14 08 46" src="https://user-images.githubusercontent.com/96294193/204205922-6c99d5d1-615d-4f7c-806d-8d32ea9347b0.png">
'Shorts' and 'Subscriptions' seemed to be switched...

**Comment by ulyngs** [comment]
Can you try updating the app, please? It seems you are using an earlier version -- this was fixed two updates ago :)
