### ISSUE TITLE
Does not working

### ISSUE THREAD

**Issue by alltogo91** [ulyngs/open-source-no-distractions-for-youtube#30]
Has no effect, even if all options are chosen

**Comment by ulyngs** [comment]
Sorry to hear! I am having a zoom call with another user tomorrow who might be experiencing the same issue.

Can you let me know:

- what device are you using? (iPhone, iPad, or Mac?)
- is the app appearing in Safari -> Extensions?

**Comment by alltogo91** [comment]
Device: Mac
Yes, it is

**Comment by ulyngs** [comment]
Ok!

Could you 
- go to Safari -> Extensions, 'No Distractions' for YouTube', and take a screenshot of what you see 
- go to Safari -> Extensions -> 'No Distractions' for YouTube' -> Edit Websites... and take a screenshot of what you see

Like so:

![Screenshot 2023-01-02 at 14 10 41](https://user-images.githubusercontent.com/23137032/210236016-86996462-d4c5-462b-a634-8c7a8318ee89.png)

![Screenshot 2023-01-02 at 14 10 41](https://user-images.githubusercontent.com/23137032/210236146-cfe523d1-4b5d-40ba-b6a4-bd5aa9036cd2.png)

**Comment by alltogo91** [comment]
![Bildschirm­foto 2023-01-02 um 14 55 43](https://user-images.githubusercontent.com/83216536/210240945-ffa1d68d-6b22-4210-b4d5-d04b57aef677.png)
![Bildschirm­foto 2023-01-02 um 14 57 06](https://user-images.githubusercontent.com/83216536/210240950-615e1a43-feed-44d7-b895-92c1b3bfadad.png)

**Comment by ulyngs** [comment]
The settings seems ok.

- are you using YouTube in German? (this shouldn't be the issue though -- it still works on my computer when I change the language to German)
- can you also go to youtube.com and take a screenshot?

Afterwards, do this:
- go to Safari > Settings > Advanced, then check the box 'Show Develop menu in menu bar'
- go to youtube.com, right-click somewhere on the page and select 'Inspect element'. Click the red exclamation mark and take a screen shot (so I can have a look at what error messages are there)
![Screenshot 2023-01-02 at 15 57 03](https://user-images.githubusercontent.com/23137032/210248021-ea17d890-18bb-4a50-9352-43be2b4b5454.png)

**Comment by alltogo91** [comment]
Yes, I use Youtube in German, but enter the page via youtube.com
![Bildschirm­foto 2023-01-02 um 16 37 05](https://user-images.githubusercontent.com/83216536/210252584-540d171b-77f4-41a8-af68-382146593dd7.png)
![Bildschirm­foto 2023-01-02 um 16 38 22](https://user-images.githubusercontent.com/83216536/210252729-e69e425e-c705-439c-962b-d651b5a76f4a.png)

Hope every needed information is visible

**Comment by ulyngs** [comment]
Can you untick 'Recommended videos' then take a screen shot again?

**Comment by alltogo91** [comment]
![Bildschirm­foto 2023-01-02 um 18 16 28](https://user-images.githubusercontent.com/83216536/210262158-a3bbc372-7d85-4bad-b375-8a5974778e58.png)

If i click on Shorts they still available.

**Comment by ulyngs** [comment]
Ah great, so it does work after all!!

Can you:
- confirm if it is only the 'shorts' button that does not work? (i.e., it's still there if you untick the box)
- try switching you language to English and see if it works then? (it might be that the CSS selector I use is sensitive to differences in language)

**Comment by alltogo91** [comment]
![Bildschirm­foto 2023-01-02 um 18 58 20](https://user-images.githubusercontent.com/83216536/210265486-cc7a82cd-f596-4570-b55c-f03a31b419cd.png)

Untick all options, and it works =) 
Just for troubleshooting purposes...i switch to English, tick option => not working again...

Thanks for the support.
Finite a good extention against distraction, money well invested :D

**Comment by ulyngs** [comment]
If you click 'save settings', does it still show everything if you go to English and back?

**Comment by alltogo91** [comment]
Yes... the behave looks like the booleans of the checkbox are reversed

**Comment by ulyngs** [comment]
Is it because it is confusing a ticked checkbox means that it shown, not hidden?

I was thinking about this, and the reason I designed it this way was that ticking a box to turn something *off* actually felt *more* confusing.

What if I add a heading that says 'Content to show' above the checkboxes? Do you think that would make it feel like it wasn't reversed?

**Comment by alltogo91** [comment]
My thought was, I have an extention here with which I have a function that helps me to not distract myself (which one? just the ones I choose), so I assumed that I would check the checkbox. But I think that's a personal observation...a headline like you suggest is a good idea and doesn't make it unnecessarily complicated for those who are already used to it.

**Comment by ulyngs** [comment]
I see what you mean.

Hmm but I think it is confusing that a checkbox like this means that it is 'off':
<img width="140" alt="image" src="https://user-images.githubusercontent.com/23137032/210331582-43befe8d-00dd-4b9a-8111-b0bc93a146a1.png">

What do you think of this idea: When you check the checkbox, it doesn't show a checkmark, but instead a prohibition sign, like this:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/23137032/210332021-38b631e6-2015-477d-860b-f3b9e8499da1.png">

**Comment by alltogo91** [comment]
Perfect  👍

**Comment by ulyngs** [comment]
@alltogo91 what do you think of this solution

![image](https://user-images.githubusercontent.com/23137032/210592885-2a617c8a-1886-4d71-a6a4-fcb463a68150.png)
