### ISSUE TITLE
Feature request: Hide Library

### ISSUE THREAD

**Issue by OscarPalafox** [ulyngs/open-source-no-distractions-for-youtube#32]
Hi!

I just purchased your extension for iOS, and I have to say it works great, so thank you for making it! I was wondering if you could please add an option to remove the Library as well. Hopefully it's not very complex. If you give me some pointers, I could even try opening a PR myself, but I haven't done any swift, so I think it'll be more time in the end for you.

Thanks again!

**Comment by ulyngs** [comment]
done w/ 97d6cb9f316d2f55c18d2986f71c473a8897a60b

An update will come out in a couple of days!
