### ISSUE TITLE
How to stop wait timer?

### ISSUE THREAD

**Issue by Duckgon** [ulyngs/open-source-no-distractions-for-youtube#40]
I was testing a new feature regarding the wait timer, but I accidently set the timer too high and I want to return back to the settings again.

I already tried re-installing the app but it still won't give me access to the settings.

![IMG_0088](https://user-images.githubusercontent.com/116478806/230706480-b5dac84f-d19f-4a13-a5ce-1f5dff643a51.jpg)

**Comment by ulyngs** [comment]
It was bound to happen, wasn't it? :joy:

I should fix a maximum value for this, that is checked on the backend before the user input it accepted. What do you think the limit should be? I'm thinking 300 (i.e. 5 minutes)?

For now, here is a 'hack' for you to override the timer (this is very dangerous knowledge if you want to hold yourself accountable):
- go to Safari > Settings, click Advanced, then select "Show Develop menu in menu bar"
- go youtube, then click the extension icon
- right-click on the delay popup, then click 'Inspect Element'
- double-click on `style="display: block"` for the div with `id="delay-content"` and change it to `style="display: none;"
- double-click on `style="display: none"` for the div with `id="popup-content"` and change it to `style="display: block;"

<img width="650" alt="image" src="https://user-images.githubusercontent.com/23137032/230846967-a21904f3-372b-4938-bff4-7b9000ca4174.png">

**Comment by ulyngs** [comment]
I have just submitted an update which caps the delay time at 600 seconds and tells the user that this is the limit if you try to set it higher.

Let's see if this addresses people's need -- let me know what you think!

**Comment by Duckgon** [comment]
I think that's a great idea, definitely a way to prevent silly mistakes such as mine. 

Will the update reset my current mistake? Because so far the problem persists. 

I'm on IOS and I don't think there's a way for me to "Inspect element", and I don't have access to a mac.

Thank you for your help!

**Comment by ulyngs** [comment]
Ah thanks for adding that detail!

I will make an amendment to the update that will reset the delay time to five seconds if it's bigger than 600.
