### ISSUE TITLE
Feature request: hide YouTube shorts on search results page

### ISSUE THREAD

**Issue by derreck503** [ulyngs/open-source-no-distractions-for-youtube#41]
Homepage is free of #Shorts, is possible to do the same for the search results page? <img width="1027" alt="Screenshot 2023-04-11 at 8 44 25 PM" src="https://user-images.githubusercontent.com/18196165/231325738-bb1e31da-76a6-4a91-ab26-ffb575df8b1a.png">

**Comment by ulyngs** [comment]
Just fixed this and about to submit the update to the app store -- it should be out in a day or two!

**Comment by derreck503** [comment]
Thank you @ulyngs!
