### ISSUE TITLE
Feature request: load video player in "theater mode" by default

### ISSUE THREAD

**Issue by derreck503** [ulyngs/open-source-no-distractions-for-youtube#44]
Would fill out the empty "Related/Up next videos" space and place the focus on the video 🙏

**Comment by ulyngs** [comment]
Hmm... I did this at this point but I reverted to leave the space untouched, because the sidebar is sometimes used to show the Chat or timestamps, in addition to the related videos.

How about I add an additional checkbox gives people the choice to remove the related videos space or not?

**Comment by ulyngs** [comment]
added in latest update
