### ISSUE TITLE
Improvement: Visual feedback on comment-toggle button

### ISSUE THREAD

**Issue by Teufelchen1** [ulyngs/open-source-no-distractions-for-youtube#5]
Hi 🙋‍♀️ 

I find it displeasing that the button for enabling / disabling provides none feedback. In particular:

- No feedback upon hovering
- No feedback upon clicking
- No feedback wether or not comments are enabled(i.e. changing color to red when comments are shown)

**Comment by ulyngs** [comment]
Apologies for the long delay in getting to this.

I've finally fixed this (e.g. 6c2fa61) and submitted an updated version to the App Store - the update should be available in a couple of days, let me know what you think!
