### ISSUE TITLE
Random video loading on feed

### ISSUE THREAD

**Issue by tamsika** [ulyngs/open-source-no-distractions-for-youtube#52]
Just installed your app, I checked all the boxes except the search bar on the extension. My feed is black for few second and then it starts to play a preview of a random video.

**Comment by ulyngs** [comment]
This is the 'auto-playing previews' -- you can find the instructions for turning them in the extension by tapping the arrow next to 'Auto-playing previews':

- Tap your account image > Settings > Account > untick 'Video previews'

Does that work?

**Comment by tamsika** [comment]
Thank you so much, sorry for the dumb question.

**Comment by ulyngs** [comment]
No such thing as a dumb question! I am sure many others have had the same confusion -- have you got any suggested rewording that would have it clearer for you? :)
