### ISSUE TITLE
hide the profile pictures on YouTube (channel name only without profile pictures)

### ISSUE THREAD

**Issue by Haizam3** [ulyngs/open-source-no-distractions-for-youtube#55]
When we open a YouTube video or even search for a YouTube video. There is the image of the channel shown next to the channel name. If we could have a feature for only the channel name to be shown without the channel profile picture.

Even in comments we see the channel name and its profile picture next to it. If we could have a feature to avoid the profile pics?

**Comment by ulyngs** [comment]
This will be fixed in the next update!

**Comment by ulyngs** [comment]
This should be fixed now -- I also fixed that thumbnails were still showing for playlists

**Comment by Haizam3** [comment]
Thank you for this and letting me know but in the comment section the account images are still shown.
The problem is that There are some bots these days commenting with certain profile pics. 


Sent from Yahoo Mail for iPhone


On Tuesday, November 7, 2023, 10:26 PM, Ulrik Lyngs ***@***.***> wrote:




This should be fixed now -- I also fixed that thumbnails were still showing for playlists
