### ISSUE TITLE
Disable Youtube Shorts entirely 

### ISSUE THREAD

**Issue by RicoSchmitt** [ulyngs/open-source-no-distractions-for-youtube#58]
I would like to request a feature enhancement that would extend the blocking capabilities of the app to also cover YouTube Shorts. The presence of Shorts is a significant source of distraction due to their brevity and the ease with which they can be inadvertently binged.

This would include:
Search Results Filtering: When searching for content on YouTube, Shorts should be omitted from the results to ensure that only relevant, non-distracting content is presented. At the moment  I can only block them in the menu bar but get them displayed when I search for something.

**Comment by ulyngs** [comment]
Great points, I'll get this on the list for the next update!

**Comment by RicoSchmitt** [comment]
Thank you, highly appreciated!

**Comment by ulyngs** [comment]
Interesting, I actually thought I'd already fixed this -- when I search for something on my computer, then block shorts, shorts also disappear in the search results.

Could you let me know:
- are you on iPhone / mac / iPad?
- what version of my app are you using?

**Comment by RicoSchmitt** [comment]
Mac: i9 (maybe a x86 issue ?) 
Safari: 17.0
"No disractions" for YouTube: 3.14

Thank you, for looking into this!

**Comment by RicoSchmitt** [comment]
I just checked this: I have the same issue on Iphone/Ipad.

**Comment by ulyngs** [comment]
OK -- can you add a couple of screenshots, then I'll try to replicate it?

**Comment by RicoSchmitt** [comment]
Sure: Here you go:
<img width="990" alt="image" src="https://github.com/ulyngs/open-source-no-distractions-for-youtube/assets/114837164/b2ea844c-2311-46bb-97ff-02983fab215e">

**Comment by diksown** [comment]
I second this! Shorts still appear on the search section. IOS 17.1.2 / Iphone 11 / Safari
Not sure of how to get the app version, but the app store says it’s updated

**Comment by ulyngs** [comment]
fixed in upcoming version v 3.15, merry xmas! :D
