### ISSUE TITLE
The shorts in my right bar is still available (cannot switch off)

### ISSUE THREAD

**Issue by Angguguuu** [ulyngs/open-source-no-distractions-for-youtube#66]
Hello, fan from Malaysia here ! Thanks for creating such an awesome app! Truly appreciate it! 

just want to ask how can I remove the shorts on left side bar? 
I’m able to remove it by using mindshield on my iPhone 8 Plus, but I can’t remove it by using “No distraction” from YouTube on my iPad Air 4 

iOS 17.4.1

Attaching pictures as below
![IMG_3074](https://github.com/ulyngs/open-source-no-distractions-for-youtube/assets/169286269/2a8a44d3-6694-49e7-b2dd-ae12835a3461)

Update: it’s okay 🤣 i figured it out

**Comment by ulyngs** [comment]
Great to hear that you figured it out! What was the issue?
