### ISSUE TITLE
YouTube Shorts are not being blocked or blurred

### ISSUE THREAD

**Issue by paul-rami** [ulyngs/open-source-no-distractions-for-youtube#71]
No working option to block Shorts, so it loses all of its anti-addictive power, as Shorts are the most addictive.

**Comment by ulyngs** [comment]
Hi Paul, can you let me know what version you're on? I submitted an updated version last week, which addressed Shorts not being hidden after a change by YouTube to the site structure

**Comment by paul-rami** [comment]
Sorry, my bad I was not on the latest version. All good now and thanks for this amazing app, the only one that makes you bearable and healthy!
