### ISSUE TITLE
Hiding the Shorts section 

### ISSUE THREAD

**Issue by Jusloco** [ulyngs/open-source-no-distractions-for-youtube#8]
A function that hides the shorts section of youtube, since it is often more distracting than recommmended, and allowing it to be toggled on and off with the extension button of safari

**Comment by ulyngs** [comment]
Thanks for opening this, I think it's a good suggestion! 

I've been furiously busy the past months, and will be for the next few weeks, but I will try to find time to implement this in the first week of April.

**Comment by Jusloco** [comment]
Sounds good Ulrik.
Thank you very much

**Comment by ulyngs** [comment]
aaaaand it's done! If you update to the version currently on the app store, the extension now hides the shorts section by default. It can be toggled on from the extension icon.

**Comment by Jusloco** [comment]
Ulrik you’re the man!!!
Thanks so much for this
I hope it’s giving you some passive income
I’ll recommend it to my friends
